### ISSUE TITLE
Slight text positioning error

### ISSUE THREAD

**Issue by lloll4321** [PenangScienceCluster/PythonCFA#19]
There is a slight error in the 'python_course.pdf' in intro/docs regarding pages 9 and 10.
At the end of page 9, where it says "Finally, we execute our function with:", it's immediately followed by Code 2 instead of "hello()". Instead, the "hello()" function can be found directly underneath Code 2.
![image](https://github.com/PenangScienceCluster/PythonCFA/assets/165871226/17667c5f-644c-4dc1-bbbd-66d720ba6a0c)

**Comment by chanjuping** [comment]
Thanks for noticing the formatting issue.

I have changed up the document with https://github.com/PenangScienceCluster/PythonCFA/commit/7fc10e847030eac086ef066a0013d3f352a484b5 and https://github.com/PenangScienceCluster/PythonCFA/commit/13b6ccaafb445045c77f71411e4dbdf3b6c1d21b to remove the ambiguity and fix up the document a little.

You can also submit a pull request by directly downloading the fodt file in LibreOffice, making the changes, and submitting a pull request.
