### ISSUE TITLE
Python Mini Project

### ISSUE THREAD

**Issue by events-psc** [PenangScienceCluster/PythonCFA#5]
https://github.com/PenangScienceCluster/PythonCFA/blob/3c505072e22963d3a51ced20aab7822ca8b2abf3/intro/docs/python_course.fodt#L3485

**Comment by chanjuping** [comment]
Unclear what you are referring to. Please provide more details. Please reopen with more details if still relevant.

**Comment by chanjuping** [comment]
No worries. This is pretty much the standard procedure for processing bug reports :-)

Thanks for trying out the system.
